server:
  port: 9000
spring:
  application:
    name: spring-cloud-api-gateway
  main:
    web-application-type: reactive
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedHeaders:
#              - content-type
#            allowedMethods:
#              - GET
#              - POST
#
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eurekaServer:8761/eureka
#    fetchRegistry: true
#    registerWithEureka: true
