server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://mysqlservice:3306/authenticatemuzix_db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver: com.mysql.cj.jdbc.Driver
  #    url: ${MYSQL_URL:jdbc:mysql://mysqlservice:3306/authenticate_db}
  #    username: ${MYSQL_USERNAME:root}
  #    password: ${MYSQL_PASSWORD:root}
  #    driver: ${MYSQL_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  application:
    name: user-authentication-service
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eurekaServer:8761/eureka
#    fetchRegistry: true
#    registerWithEureka: true
